--[[
	macc + FOV90 — encoded loader
	Opening this raw link shows mostly gibberish.
	Use: loadstring(game:HttpGet("YOUR_RAW_GITHUB_URL"))()
]]

local _b = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local function _d(data)
	data = string.gsub(data, "[^" .. _b .. "=]", "")
	return (data:gsub(".", function(x)
		if x == "=" then return "" end
		local r, f = "", (_b:find(x) - 1)
		for i = 6, 1, -1 do
			r = r .. (f % 2 ^ i - f % 2 ^ (i - 1) > 0 and "1" or "0")
		end
		return r
	end):gsub("%d%d%d?%d?%d?%d?%d?%d?", function(x)
		if #x ~= 8 then return "" end
		local c = 0
		for i = 1, 8 do
			c = c + (x:sub(i, i) == "1" and 2 ^ (8 - i) or 0)
		end
		return string.char(c)
	end))
end

local _p = [=[
LS1bWwoJbWFjYyArIEZPVjkwIG1lcmdlZAoJQmxhY2sgcGFsbGV0ICsgcGVyZm9ybWFuY2UgZm9nIC8gRk9WCl1dCgpsb2NhbCBUd2VlblNlcnZpY2UgPSBnYW1lOkdldFNlcnZpY2UoIlR3ZWVuU2VydmljZSIpCmxvY2FsIFBsYXllcnMgPSBnYW1lOkdldFNlcnZpY2UoIlBsYXllcnMiKQpsb2NhbCBMaWdodGluZyA9IGdhbWU6R2V0U2VydmljZSgiTGlnaHRpbmciKQpsb2NhbCBMb2NhbFBsYXllciA9IFBsYXllcnMuTG9jYWxQbGF5ZXIKCi0tID09PT09PT09PT0gQmxhY2sgcGFsbGV0ID09PT09PT09PT0KbG9jYWwgUkVGTEVDVEFOQ0UgPSAwLjI4CmxvY2FsIENPTE9SX1RJTUUgPSAwLjcKCmxvY2FsIGZ1bmN0aW9uIGFwcGx5QmxhY2sob2JqKQoJaWYgbm90IG9iaiBvciBub3Qgb2JqLlBhcmVudCB0aGVuIHJldHVybiBlbmQKCglmb3IgXywgcGFydCBpbiBpcGFpcnMob2JqOkdldERlc2NlbmRhbnRzKCkpIGRvCgkJaWYgcGFydDpJc0EoIkJhc2VQYXJ0IikgdGhlbgoJCQlsb2NhbCBvbGQgPSBwYXJ0OkZpbmRGaXJzdENoaWxkKCJGYWtlUmVmbGVjdGlvbiIpCgkJCWlmIG9sZCB0aGVuIG9sZDpEZXN0cm95KCkgZW5kCgoJCQlUd2VlblNlcnZpY2U6Q3JlYXRlKAoJCQkJcGFydCwKCQkJCVR3ZWVuSW5mby5uZXcoQ09MT1JfVElNRSwgRW51bS5FYXNpbmdTdHlsZS5RdWFkLCBFbnVtLkVhc2luZ0RpcmVjdGlvbi5PdXQpLAoJCQkJewoJCQkJCUNvbG9yID0gQ29sb3IzLmZyb21SR0IoMTAsIDEwLCAxMCksCgkJCQkJUmVmbGVjdGFuY2UgPSBSRUZMRUNUQU5DRQoJCQkJfQoJCQkpOlBsYXkoKQoKCQkJbG9jYWwgaGlnaGxpZ2h0ID0gSW5zdGFuY2UubmV3KCJIaWdobGlnaHQiKQoJCQloaWdobGlnaHQuTmFtZSA9ICJGYWtlUmVmbGVjdGlvbiIKCQkJaGlnaGxpZ2h0LkFkb3JuZWUgPSBwYXJ0CgkJCWhpZ2hsaWdodC5GaWxsQ29sb3IgPSBDb2xvcjMuZnJvbVJHQigyNTUsIDI1NSwgMjU1KQoJCQloaWdobGlnaHQuRmlsbFRyYW5zcGFyZW5jeSA9IDAuOTMKCQkJaGlnaGxpZ2h0Lk91dGxpbmVUcmFuc3BhcmVuY3kgPSAxCgkJCWhpZ2hsaWdodC5EZXB0aE1vZGUgPSBFbnVtLkhpZ2hsaWdodERlcHRoTW9kZS5PY2NsdWRlZAoJCQloaWdobGlnaHQuUGFyZW50ID0gcGFydAoJCWVuZAoJZW5kCmVuZAoKbG9jYWwgZm9sZGVyTmFtZSA9IExvY2FsUGxheWVyLk5hbWUgLi4gIlNwYXduZWRJblRveXMiCmxvY2FsIGZvbGRlciA9IHdvcmtzcGFjZTpGaW5kRmlyc3RDaGlsZChmb2xkZXJOYW1lKQppZiBub3QgZm9sZGVyIHRoZW4KCWZvbGRlciA9IHdvcmtzcGFjZTpXYWl0Rm9yQ2hpbGQoZm9sZGVyTmFtZSwgMTApCmVuZAoKaWYgZm9sZGVyIHRoZW4KCWZvbGRlci5DaGlsZEFkZGVkOkNvbm5lY3QoZnVuY3Rpb24ob2JqKQoJCWlmIG9iai5OYW1lID09ICJQYWxsZXRMaWdodEJyb3duIiB0aGVuCgkJCXRhc2sud2FpdCgwLjI1KQoJCQlpZiBvYmogYW5kIG9iai5QYXJlbnQgdGhlbgoJCQkJYXBwbHlCbGFjayhvYmopCgkJCWVuZAoJCWVuZAoJZW5kKQoKCWZvciBfLCBvYmogaW4gaXBhaXJzKGZvbGRlcjpHZXRDaGlsZHJlbigpKSBkbwoJCWlmIG9iai5OYW1lID09ICJQYWxsZXRMaWdodEJyb3duIiB0aGVuCgkJCXRhc2suc3Bhd24oZnVuY3Rpb24oKQoJCQkJdGFzay53YWl0KDAuMjUpCgkJCQlhcHBseUJsYWNrKG9iaikKCQkJZW5kKQoJCWVuZAoJZW5kCmVsc2UKCXdhcm4oIuaJvuS4jeWIsOizh+aWmeWkvu+8miIgLi4gZm9sZGVyTmFtZSkKZW5kCgotLSBHcmFzcyBncmF5CmZvciBfLCBvYmogaW4gaXBhaXJzKHdvcmtzcGFjZTpHZXREZXNjZW5kYW50cygpKSBkbwoJaWYgb2JqOklzQSgiQmFzZVBhcnQiKSBhbmQgb2JqLk1hdGVyaWFsID09IEVudW0uTWF0ZXJpYWwuR3Jhc3MgdGhlbgoJCW9iai5Db2xvciA9IENvbG9yMy5mcm9tUkdCKDEyMCwgMTIwLCAxMjApCgllbmQKZW5kCgotLSBEaXNhYmxlIHBhcnRpY2xlcyAvIHRyYWlscyAvIGJlYW1zIC8gc2hhZG93cwpmb3IgXywgb2JqIGluIGlwYWlycyh3b3Jrc3BhY2U6R2V0RGVzY2VuZGFudHMoKSkgZG8KCWlmIG9iajpJc0EoIlBhcnRpY2xlRW1pdHRlciIpIG9yIG9iajpJc0EoIlRyYWlsIikgb3Igb2JqOklzQSgiQmVhbSIpIHRoZW4KCQlvYmouRW5hYmxlZCA9IGZhbHNlCgllbHNlaWYgb2JqOklzQSgiQmFzZVBhcnQiKSB0aGVuCgkJb2JqLkNhc3RTaGFkb3cgPSBmYWxzZQoJZW5kCmVuZAoKZm9yIF8sIG9iaiBpbiBpcGFpcnMoTGlnaHRpbmc6R2V0Q2hpbGRyZW4oKSkgZG8KCWlmIG9iajpJc0EoIlBvc3RFZmZlY3QiKSB0aGVuCgkJb2JqLkVuYWJsZWQgPSBmYWxzZQoJZW5kCmVuZAoKLS0gPT09PT09PT09PSBGT1Y5MCAvIHBlcmZvcm1hbmNlIGZvZyA9PT09PT09PT09CmxvY2FsIGZ1bmN0aW9uIGFwcGx5UGVyZm9ybWFuY2VGb2coKQoJbG9jYWwgbGlnaHRpbmcgPSBnYW1lOkdldFNlcnZpY2UoIkxpZ2h0aW5nIikKCglsaWdodGluZy5Gb2dFbmQgPSA1MDAKCWxpZ2h0aW5nLkZvZ0NvbG9yID0gQ29sb3IzLm5ldygwLjYsIDAuNiwgMC42KQoJbGlnaHRpbmcuRm9nU3RhcnQgPSA1MAoKCWxpZ2h0aW5nLkdsb2JhbFNoYWRvd3MgPSBmYWxzZQoJbGlnaHRpbmcuQnJpZ2h0bmVzcyA9IDEuMgoKCWxvY2FsIGNhbSA9IHdvcmtzcGFjZS5DdXJyZW50Q2FtZXJhCglpZiBjYW0gdGhlbgoJCWNhbS5GaWVsZE9mVmlldyA9IDkwCgllbmQKCglwY2FsbChmdW5jdGlvbigpCgkJbGlnaHRpbmcuT3V0bGluZXMgPSBmYWxzZQoJZW5kKQoJcGNhbGwoZnVuY3Rpb24oKQoJCWxpZ2h0aW5nLkVudmlyb25tZW50U3BlY3VsYXJTY2FsZSA9IDAKCQlsaWdodGluZy5FbnZpcm9ubWVudERpZmZ1c2VTY2FsZSA9IDAuNQoJZW5kKQoJcGNhbGwoZnVuY3Rpb24oKQoJCWxpZ2h0aW5nLkZvZ0RlbnNpdHkgPSAwLjAyCgllbmQpCmVuZAoKYXBwbHlQZXJmb3JtYW5jZUZvZygpCgpMaWdodGluZy5DaGFuZ2VkOkNvbm5lY3QoZnVuY3Rpb24ocHJvcGVydHkpCglpZiBwcm9wZXJ0eSA9PSAiRm9nRW5kIiBvciBwcm9wZXJ0eSA9PSAiRm9nQ29sb3IiIG9yIHByb3BlcnR5ID09ICJGb2dTdGFydCIgdGhlbgoJCXRhc2sud2FpdCgwLjEpCgkJYXBwbHlQZXJmb3JtYW5jZUZvZygpCgllbmQKZW5kKQoKdGFzay5zcGF3bihmdW5jdGlvbigpCgl3aGlsZSB0cnVlIGRvCgkJdGFzay53YWl0KDUpCgkJYXBwbHlQZXJmb3JtYW5jZUZvZygpCgllbmQKZW5kKQoKcHJpbnQoIlttYWNjK0ZPVjkwXSBCbGFjayBwYWxsZXQgKyBwZXJmb3JtYW5jZSBmb2cgLyBGT1YgOTAgbG9hZGVkIikK
]=]

local ok, err = pcall(function()
	loadstring(_d(_p))()
end)
if not ok then
	warn("[macc+FOV90] load failed:", err)
end
